"""Pydantic schemas for app API v1."""

from datetime import datetime
from decimal import Decimal

from pydantic import BaseModel, EmailStr


# ─── Thread ──────────────────────────────────────────────────────────────────

class ThreadOut(BaseModel):
    thread_id: str
    subject: str | None
    created_at: datetime

    model_config = {"from_attributes": True}


# ─── Message ─────────────────────────────────────────────────────────────────

class IngestMessageIn(BaseModel):
    """Incoming email from IMAP worker."""

    message_id: str
    author_email: str
    sender_name: str | None = None
    reply_to_email: str | None = None
    subject: str | None = None
    body_text: str | None = None
    body_html: str | None = None
    headers_json: dict | None = None
    thread_id: str
    # Idempotency key for the PROCESS_INCOMING outbox task
    task_key: str
    # Trace ID generated by the calling service (mail_app IMAP worker) per
    # received email; propagated into the PROCESS_INCOMING task payload.
    run_id: str | None = None


class OutgoingMessageIn(BaseModel):
    """Outgoing email queued by agent."""

    message_id: str
    author_email: str
    subject: str | None = None
    body_text: str | None = None
    body_html: str | None = None
    headers_json: dict | None = None
    thread_id: str
    task_key: str
    # Optional extra payload forwarded to the SMTP worker
    smtp_payload: dict | None = None
    # Trace ID inherited from the originating operation; mirrors into smtp_payload
    # so the SMTP worker can rebind it when picking up the SEND_SMTP task.
    run_id: str | None = None


class MessageOut(BaseModel):
    message_id: str
    thread_id: str
    author_email: str
    body_text: str | None
    body_html: str | None
    headers_json: dict | None
    run_id: str | None = None
    created_at: datetime

    model_config = {"from_attributes": True}


class IngestOut(BaseModel):
    message: MessageOut
    thread: ThreadOut
    task_id: str
    task_created: bool


class OutgoingOut(BaseModel):
    message: MessageOut
    thread: ThreadOut
    task_id: str
    task_created: bool


# ─── Outbox ───────────────────────────────────────────────────────────────────

class DequeueIn(BaseModel):
    task_type: str | None = None
    limit: int = 10
    claim_ttl_seconds: int = 300


class OutboxTaskOut(BaseModel):
    id: str
    task_type: str
    email_id: str | None
    payload_json: dict | None
    task_key: str
    status: str
    attempt: int
    claim_token: str | None
    claim_until: datetime | None
    run_id: str | None = None
    created_at: datetime
    updated_at: datetime

    model_config = {"from_attributes": True}


class UpdateStatusIn(BaseModel):
    status: str  # DONE | RETRYING | FAILED
    claim_token: str
    error: str | None = None
    next_retry_at: datetime | None = None


# ─── Approve Deal Snapshots ──────────────────────────────────────────────────

class ApproveDealSnapshotIn(BaseModel):
    calc_id: str
    task_id: str
    run_id: str | None = None
    calc_dttm: datetime | None = None
    # Financial
    policy_rate: Decimal | None = None
    ets: Decimal | None = None
    for_rate: Decimal | None = None
    eva_target: Decimal | None = None
    eva_indicative: Decimal | None = None
    asv: Decimal | None = None
    option_price: Decimal | None = None
    crl: Decimal | None = None
    cfc_so: Decimal | None = None
    cfc_ets: Decimal | None = None
    cfc_for_rate: Decimal | None = None
    cfc_eva_target: Decimal | None = None
    cfc_eva_indicative: Decimal | None = None
    cfc_asv: Decimal | None = None
    cfc_option_price: Decimal | None = None
    cfc_k_liq_fund: Decimal | None = None
    # Deal conditions
    inn: str | None = None
    term_days: int | None = None
    volume: float | None = None
    currency: str | None = None
    rate: float | None = None
    rate_type: str | None = None
    product: str | None = None
    basis: str | None = None
    optionality: str | None = None


class ApproveDealSnapshotOut(BaseModel):
    calc_id: str
    task_id: str
    run_id: str | None
    calc_dttm: datetime
    # Financial
    policy_rate: Decimal | None
    ets: Decimal | None
    for_rate: Decimal | None
    eva_target: Decimal | None
    eva_indicative: Decimal | None
    asv: Decimal | None
    option_price: Decimal | None
    crl: Decimal | None
    cfc_so: Decimal | None
    cfc_ets: Decimal | None
    cfc_for_rate: Decimal | None
    cfc_eva_target: Decimal | None
    cfc_eva_indicative: Decimal | None
    cfc_asv: Decimal | None
    cfc_option_price: Decimal | None
    cfc_k_liq_fund: Decimal | None
    # Deal conditions
    inn: str | None
    term_days: int | None
    volume: float | None
    currency: str | None
    rate: float | None
    rate_type: str | None
    product: str | None
    basis: str | None
    optionality: str | None

    model_config = {"from_attributes": True}


# ─── Approve Tasks ───────────────────────────────────────────────────────────

class ApproveTaskIn(BaseModel):
    task_id: str
    calculation_id: str
    task_status: str
    task_dttm: datetime | None = None
    attempt_count: int = 0
    agent_answer: str | None = None
    deal_status: str | None = None
    error_message: str | None = None
    run_id: str | None = None


class ApproveTaskOut(BaseModel):
    task_id: str
    calculation_id: str
    task_dttm: datetime
    updated_at: datetime
    task_status: str
    attempt_count: int
    agent_answer: str | None
    deal_status: str | None
    error_message: str | None
    run_id: str | None = None

    model_config = {"from_attributes": True}


class UpdateApproveTaskIn(BaseModel):
    task_status: str
    deal_status: str | None = None
    agent_answer: str | None = None
    attempt_count: int | None = None
    error_message: str | None = None
    run_id: str | None = None


# ─── Deal Parsing Log ────────────────────────────────────────────────────────

class DealParsingLogIn(BaseModel):
    message_id: str
    fragment_idx: int
    fragment_text: str
    extraction_status: str = "empty"
    intent: str | None = None
    deal_number: int | None = None
    parsed_conditions: dict | None = None
    error_details: str | None = None
    warnings: dict | None = None
    run_id: str | None = None


class DealParsingLogOut(BaseModel):
    id: str
    message_id: str
    fragment_idx: int
    fragment_text: str
    extraction_status: str
    intent: str | None
    deal_number: int | None
    parsed_conditions: dict | None
    error_details: str | None
    warnings: dict | None
    run_id: str | None = None
    created_at: datetime

    model_config = {"from_attributes": True}


# ─── Deal Snapshots ──────────────────────────────────────────────────────────

class DealSnapshotIn(BaseModel):
    thread_id: str
    deal_number: int
    iteration: int
    limit_rate: Decimal
    policy_rate: Decimal
    final_rate: Decimal
    status: str
    parsing_log_id: str
    utilizes_limit: bool
    agent_text: str
    incoming_conditions: dict | None = None
    request_rate: Decimal | None = None
    avg_hist_rate: Decimal | None = None
    model_rate: Decimal | None = None
    proposed_conditions: dict | None = None
    escalation_reason: str | None = None
    run_id: str | None = None


class DealSnapshotOut(BaseModel):
    id: str
    thread_id: str
    deal_number: int
    iteration: int
    incoming_conditions: dict | None
    request_rate: Decimal | None
    limit_rate: Decimal
    avg_hist_rate: Decimal | None
    model_rate: Decimal | None
    policy_rate: Decimal
    final_rate: Decimal
    proposed_conditions: dict | None
    status: str
    escalation_reason: str | None
    parsing_log_id: str
    run_id: str | None = None
    created_at: datetime
    utilizes_limit: bool
    agent_text: str

    model_config = {"from_attributes": True}


# ─── Consultant Agent Logs ───────────────────────────────────────────────────

class ConsultantAgentLogIn(BaseModel):
    """Single Q/A round of the СЮЛ consultant agent."""

    id: str
    session_id: str
    message_id: str
    user_id: str
    question: str
    agent_branch: str | None = None
    agent_answer: str | None = None
    question_dttm: datetime | None = None
    answer_dttm: datetime | None = None
    source_system: str = "support"
    run_id: str | None = None


class ConsultantAgentLogAnswerIn(BaseModel):
    """Patch payload for filling in a deferred answer."""

    agent_answer: str
    answer_dttm: datetime | None = None
    agent_branch: str | None = None


class ConsultantAgentLogOut(BaseModel):
    id: str
    question_dttm: datetime
    session_id: str
    message_id: str
    user_id: str
    question: str
    agent_branch: str | None
    agent_answer: str | None
    answer_dttm: datetime | None
    source_system: str
    run_id: str | None = None

    model_config = {"from_attributes": True}
